#pragma once

enum class ArchPackageParsingState {
    PARSING_NONE,
    PARSING_NAME,
    PARSING_VERSION,
    PARSING_DESCRIPTION,
    PARSING_FILENAME,
    PARSING_SHA256,
    PARSING_DEPENDENCIES,
    PARSING_OPTIONAL_DEPENDENCIES,
    PARSING_CONFLICTS,
    PARSING_LICENSE,
    PARSING_COMPRESSED_SIZE,
    PARSING_UNCOMPRESSED_SIZE,
    DONE
};